# Generated by Django 4.2.13 on 2024-06-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructores',
            name='programas',
            field=models.ManyToManyField(to='Principal.programa'),
        ),
    ]
