# Generated by Django 4.2.13 on 2024-06-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_instructores_programas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructores',
            name='programas',
        ),
        migrations.AddField(
            model_name='instructores',
            name='categoria',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Fuerza', 'Fuerza'), ('Movimiento', 'Movimiento'), ('Flexibilidad', 'Flexibilidad')], default='A definir manualmente.', max_length=40),
        ),
    ]
